project_id = "fzavetncuqopdbxfdnai"

[functions.ai-research]
verify_jwt = true

[functions.ai-generate]
verify_jwt = true

[functions.scrape-competitor]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true
